version: '3.8'
services:
    web-server:
        container_name: nginx-react-app
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        args: 
            - repoarg=${git_repo}
