version: '3.3'
services:
    web-server:
        container_name: nginx-react-app
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - repoarg=${git_repo}
        ports:
            - 80:80
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
